### PR TITLE
Adds support for HTTP proxy environemnt variables

### LINKED ISSUE #368: Respect the HTTPS_PROXY environment variable
Follow-up from #363: it would be great if MCS could honour the HTTPS_PROXY environment variable. People who are behind a proxy should not be bothered with setting the `https.proxyHost` and `https.proxyPort` JVM system variables manually.

### PR DESCRIPTION
**Pull request by jwedel**
Fixes #368

### CODE REVIEW

**Review by mthmulders — APPROVED** [review]
Awesome, thanks a lot @jwedel. I will merge this and soon publish a release, probably next week.

**Comment by jwedel** [comment]
@mthmulders what about the failing mutation tests? How can I run them? I just did the mvn verify.

**Comment by mthmulders** [comment]
> @mthmulders what about the failing mutation tests? How can I run them? I just did the mvn verify.

On second observation, this may be a different issue. Nevertheless, I'll see how important it is and whether we need to deal with it or not.

**Comment by jwedel** [comment]
> > @mthmulders what about the failing mutation tests? How can I run them? I just did the mvn verify.
> 
> On second observation, this may be a different issue. Nevertheless, I'll see how important it is and whether we need to deal with it or not.

Just FYI, you may have seen it in the changes, I needed to add a command line option to to failsafe to allow changing the env vars.

When the mutation test also run those tests, the need the same Java args.

**Comment by mthmulders** [comment]
> > On second observation, this may be a different issue. Nevertheless, I'll see how important it is and whether we need to deal with it or not.
> 
> Just FYI, you may have seen it in the changes, I needed to add a command line option to to failsafe to allow changing the env vars.
> 
> When the mutation test also run those tests, the need the same Java args.

Good catch, that was the cause! I'll include that when I merge it - but it will not fix the integration issue that I mentioned earlier.

**Comment by mthmulders** [comment]
Closed with 7c2280f480bd4e888c0d00b9cb219a51dabe932f, thanks @jwedel!

**Pull request closed without merging**
